# db config
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: team_f
    password: green502
    url: jdbc:mariadb://192.168.0.144:3306/team_f

# mybatis config
mybatis:
  type-aliases-package: com.green.team_f
  mapper-locations: mapper/**/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html
    operations-sorter : method

file:
  dir: /home/download
