# db config
spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: green502
    url: jdbc:mariadb://localhost:3306/practice

# mybatis config
mybatis:
  type-aliases-package: com.green.project
  mapper-locations: mapper/**/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/download/F_Hpic

file3:
  dir: D:/download/exrec


file10:
  dir: D:/download/foodcate


file20:
  dir: D:/download/foodrecord